### ISSUE TITLE
TODO be-2 milestones

### ISSUE THREAD

**Issue by RaulinN** [dedis/student20_pop#115]
- [x] `id` should be `null` if `id` cannot be read by the server (#96)
- [x] what happens when the server receives an error message as input?
- [x] implement changes proposed in #99 
- [x] add roll-call events _(half done)_
- [x] New way to compute hashes
- [x] more unit tests/documentation
