### ISSUE TITLE
TODO fe-1-wuersch milestones

### ISSUE THREAD

**Issue by imaximumGit** [dedis/student20_pop#144]
- [x] Send request to back-end when the user create a meeting
- [x] Send request to back-end when the user create a roll-call
- [x] Add UI test (target reducer folder)
- [x] Enter date and time in web interface
